# Generated by Django 5.2 on 2026-10-01 10:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_grade_workerclass'),
        ('employee', '0005_alter_employee_phone_and_more'),
        ('krew_company_onboarding', '0025_phone_number_10_digit_validation'),
        ('krew_payroll', '0006_payslip_unique_payslip_per_employee_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], max_length=10, verbose_name='Type')),
                ('code', models.CharField(editable=False, max_length=20, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('company_id', models.ForeignKey(db_column='company_id', editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Pay Component',
                'verbose_name_plural': 'Pay Components',
                'db_table': 'krew_payroll_pay_component',
                'ordering': ['type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayComponentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('version_no', models.PositiveIntegerField(verbose_name='Version')),
                ('publish_state', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10, verbose_name='Publish State')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='Effective From')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Effective To')),
                ('frequency', models.CharField(choices=[('RECURRING', 'Recurring'), ('ONE_TIME', 'One-Time'), ('ON_DEMAND', 'On-Demand'), ('EXIT_TRIGGERED', 'Exit-Triggered')], default='RECURRING', max_length=20, verbose_name='Frequency')),
                ('recurring_interval', models.CharField(blank=True, choices=[('EVERY_CYCLE', 'Every Cycle'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half-Yearly'), ('ANNUAL', 'Annual')], max_length=20, null=True, verbose_name='Recurring Interval')),
                ('one_time_date', models.DateField(blank=True, null=True, verbose_name='One-Time Date')),
                ('eligibility_mode', models.CharField(choices=[('ALL', 'Include All'), ('CONDITION', 'Condition-Based'), ('SPECIFIC', 'Specific employees')], default='ALL', max_length=10, verbose_name='Eligibility')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Min Limit')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Max Limit')),
                ('disbursement_timing', models.CharField(blank=True, choices=[('FOLLOW_CADENCE', "Follow worker's payout cadence"), ('INSTANT', 'Instant / pay on accrual')], max_length=20, null=True, verbose_name='Disbursement Timing')),
                ('tax_treatment', models.CharField(blank=True, choices=[('TAXABLE', 'Taxable'), ('TAX_FREE', 'Tax-Free')], max_length=10, null=True, verbose_name='Tax Treatment')),
                ('exemption_type', models.CharField(blank=True, choices=[('FULL', 'Fully exempt'), ('UP_TO_LIMIT', 'Exempt up to a limit')], max_length=20, null=True, verbose_name='Exemption Type')),
                ('requires_proof', models.BooleanField(default=False, verbose_name='Requires Proof')),
                ('reduces_taxable_income', models.BooleanField(default=False, verbose_name='Reduces Taxable Income')),
                ('show_on_payslip', models.BooleanField(default=True, verbose_name='Show On Payslip')),
                ('payslip_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payslip Label')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('depends_on', models.JSONField(blank=True, default=list, editable=False)),
                ('component', models.ForeignKey(db_column='component_id', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='krew_payroll.paycomponent', verbose_name='Component')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Pay Component Version',
                'verbose_name_plural': 'Pay Component Versions',
                'db_table': 'krew_payroll_pay_component_details',
                'ordering': ['component_id', 'version_no'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('list_type', models.CharField(choices=[('INCLUDE', 'Include'), ('EXCLUDE', 'Exclude')], max_length=10)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='pay_component_lists', to='employee.employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('component_details', models.ForeignKey(db_column='component_details_id', on_delete=django.db.models.deletion.CASCADE, related_name='employee_lists', to='krew_payroll.paycomponentdetails')),
            ],
            options={
                'db_table': 'krew_payroll_eligibility_employee',
            },
        ),
        migrations.CreateModel(
            name='EligibilityCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('field', models.CharField(choices=[('SHIFT', 'Shift'), ('STATE', 'State'), ('SITE', 'Location / Site'), ('CTC', 'Salary (CTC)'), ('WAGE_BASE', 'Wage Base'), ('GRADE', 'Grade'), ('DESIGNATION', 'Designation'), ('WORKER_CLASS', 'Worker Class'), ('EMPLOYMENT_TYPE', 'Employment Type')], max_length=20)),
                ('operator', models.CharField(choices=[('IN', 'is in'), ('EQ', 'equals'), ('GT', 'greater than'), ('LT', 'less than'), ('BETWEEN', 'between')], max_length=10)),
                ('values', models.JSONField(blank=True, default=list)),
                ('value_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('value_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('component_details', models.ForeignKey(db_column='component_details_id', on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='krew_payroll.paycomponentdetails')),
            ],
            options={
                'db_table': 'krew_payroll_eligibility_condition',
            },
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('purpose', models.CharField(choices=[('COMPONENT_VALUE', 'What is paid / deducted'), ('EXEMPTION_LIMIT', 'Tax-free limit'), ('EMPLOYER_SHARE', 'Employer share')], max_length=20)),
                ('mode', models.CharField(choices=[('FLAT', 'Flat / Fixed Amount'), ('PERCENTAGE', 'Percentage of components'), ('FORMULA', 'Formula'), ('SLAB', 'Slab / Bracket'), ('SYSTEM_COMPUTED', 'System-Computed')], max_length=20)),
                ('flat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('base_component_ids', models.JSONField(blank=True, default=list)),
                ('base_includes_ctc', models.BooleanField(default=False)),
                ('formula', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('component_details', models.ForeignKey(db_column='component_details_id', on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='krew_payroll.paycomponentdetails')),
            ],
            options={
                'db_table': 'krew_payroll_calculation',
            },
        ),
        migrations.CreateModel(
            name='WorkSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('company_id', models.ForeignKey(db_column='company_id', editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('state', models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.PROTECT, to='krew_company_onboarding.gststateconfig', verbose_name='State')),
            ],
            options={
                'verbose_name': 'Work Site',
                'verbose_name_plural': 'Work Sites',
                'db_table': 'krew_payroll_work_site',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePayProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('ctc_annual', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CTC (annual)')),
                ('employment_type', models.CharField(blank=True, choices=[('PAYROLL', 'Employee-on-payroll'), ('CONTRACTOR_GIG', 'Contractor-Gig')], max_length=20, null=True, verbose_name='Employment Type')),
                ('payout_cadence', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BI_WEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=10, verbose_name='Payout Cadence')),
                ('company_id', models.ForeignKey(db_column='company_id', editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.OneToOneField(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='pay_profile', to='employee.employee', verbose_name='Employee')),
                ('grade', models.ForeignKey(blank=True, db_column='grade_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='base.grade', verbose_name='Grade')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('work_state', models.ForeignKey(blank=True, db_column='work_state_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='krew_company_onboarding.gststateconfig', verbose_name='Work State')),
                ('worker_class', models.ForeignKey(blank=True, db_column='worker_class_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='base.workerclass', verbose_name='Worker Class')),
                ('work_site', models.ForeignKey(blank=True, db_column='work_site_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='krew_payroll.worksite', verbose_name='Work Site')),
            ],
            options={
                'verbose_name': 'Employee Pay Profile',
                'verbose_name_plural': 'Employee Pay Profiles',
                'db_table': 'krew_payroll_employee_pay_profile',
            },
        ),
        migrations.CreateModel(
            name='CalculationSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('range_from', models.DecimalField(decimal_places=2, max_digits=12)),
                ('range_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applies_in_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('calculation', models.ForeignKey(db_column='calculation_id', on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='krew_payroll.calculation')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'db_table': 'krew_payroll_calculation_slab',
                'ordering': ['range_from'],
                'indexes': [models.Index(fields=['calculation', 'range_from'], name='ix_slab_calc_from')],
            },
        ),
        migrations.CreateModel(
            name='EmployeePayAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], max_length=10, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount')),
                ('pay_date', models.DateField(verbose_name='Pay Date')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('LOAN', 'Loan'), ('REIMBURSEMENT', 'Reimbursement'), ('ENCASHMENT', 'Leave encashment'), ('BONUS', 'Bonus'), ('PENALTY', 'Penalty')], default='MANUAL', max_length=20, verbose_name='Source')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_taxable', models.BooleanField(default=True, verbose_name='Taxable')),
                ('reduces_taxable_income', models.BooleanField(default=False, verbose_name='Reduces Taxable Income')),
                ('company_id', models.ForeignKey(db_column='company_id', editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='pay_adjustments', to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('payslip', models.ForeignKey(blank=True, db_column='payslip_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_adjustments', to='krew_payroll.payslip')),
            ],
            options={
                'verbose_name': 'Pay Adjustment',
                'verbose_name_plural': 'Pay Adjustments',
                'db_table': 'krew_payroll_employee_pay_adjustment',
                'ordering': ['pay_date', 'id'],
                'indexes': [models.Index(fields=['employee', 'pay_date'], name='ix_adjustment_emp_date'), models.Index(fields=['source', 'source_id'], name='ix_adjustment_source')],
            },
        ),
        migrations.AddConstraint(
            model_name='paycomponent',
            constraint=models.UniqueConstraint(fields=('company_id', 'code'), name='uq_pay_component_company_code'),
        ),
        migrations.AddConstraint(
            model_name='paycomponent',
            constraint=models.UniqueConstraint(fields=('company_id', 'type', 'name'), name='uq_pay_component_company_type_name'),
        ),
        migrations.AddIndex(
            model_name='paycomponentdetails',
            index=models.Index(condition=models.Q(('publish_state', 'PUBLISHED')), fields=['component', 'effective_from'], name='ix_pcd_live_version'),
        ),
        migrations.AddConstraint(
            model_name='paycomponentdetails',
            constraint=models.UniqueConstraint(fields=('component', 'version_no'), name='uq_pay_component_version'),
        ),
        migrations.AddIndex(
            model_name='eligibilityemployee',
            index=models.Index(fields=['employee'], name='ix_eligibility_employee'),
        ),
        migrations.AddConstraint(
            model_name='eligibilityemployee',
            constraint=models.UniqueConstraint(fields=('component_details', 'employee'), name='uq_eligibility_version_employee'),
        ),
        migrations.AddConstraint(
            model_name='eligibilitycondition',
            constraint=models.UniqueConstraint(fields=('component_details', 'field'), name='uq_condition_version_field'),
        ),
        migrations.AddConstraint(
            model_name='calculation',
            constraint=models.UniqueConstraint(fields=('component_details', 'purpose'), name='uq_calculation_version_purpose'),
        ),
        migrations.AddIndex(
            model_name='worksite',
            index=models.Index(fields=['state'], name='ix_work_site_state'),
        ),
        migrations.AddConstraint(
            model_name='worksite',
            constraint=models.UniqueConstraint(fields=('company_id', 'state', 'name'), name='uq_work_site_company_state_name'),
        ),
        migrations.AddIndex(
            model_name='employeepayprofile',
            index=models.Index(fields=['company_id'], name='ix_pay_profile_company'),
        ),
        migrations.AddIndex(
            model_name='employeepayprofile',
            index=models.Index(fields=['worker_class'], name='ix_pay_profile_class'),
        ),
        migrations.AddIndex(
            model_name='employeepayprofile',
            index=models.Index(fields=['grade'], name='ix_pay_profile_grade'),
        ),
        migrations.AddIndex(
            model_name='employeepayprofile',
            index=models.Index(fields=['work_state'], name='ix_pay_profile_state'),
        ),
        migrations.AddIndex(
            model_name='employeepayprofile',
            index=models.Index(fields=['work_site'], name='ix_pay_profile_site'),
        ),
    ]
