# Generated by Django 5.2 on 2026-10-01 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krew_payroll', '0009_convert_one_off_allowance_deduction_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reimbursement',
            name='allowance_id',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='allowance_id',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='exclude_employees',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='other_conditions',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='specific_employees',
        ),
        migrations.RemoveField(
            model_name='loanaccount',
            name='deduction_ids',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='installment_ids',
        ),
        migrations.DeleteModel(
            name='Allowance',
        ),
        migrations.DeleteModel(
            name='MultipleCondition',
        ),
        migrations.DeleteModel(
            name='Deduction',
        ),
    ]
