# Generated by Django 5.2 on 2026-10-01 12:17
#
# The app was renamed payroll -> krew_payroll. 0001 pins every table to its
# original payroll_<model> name, so migration state matches the physical
# tables on both fresh and existing databases; this migration then renames
# them (and their auto-created many-to-many tables) to the default
# krew_payroll_<model>. ALTER TABLE ... RENAME is metadata-only in Postgres.
#
# Existing databases must run `manage.py rename_app_label payroll krew_payroll`
# BEFORE `migrate` (see that command for why it can't be a migration).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krew_payroll', '0010_remove_allowance_deduction'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contract',
            table=None,
        ),
        migrations.AlterModelTable(
            name='encashmentgeneralsettings',
            table=None,
        ),
        migrations.AlterModelTable(
            name='filingstatus',
            table=None,
        ),
        migrations.AlterModelTable(
            name='historicalcontract',
            table=None,
        ),
        migrations.AlterModelTable(
            name='historicalpayslip',
            table=None,
        ),
        migrations.AlterModelTable(
            name='loanaccount',
            table=None,
        ),
        migrations.AlterModelTable(
            name='overrideleaverequest',
            table=None,
        ),
        migrations.AlterModelTable(
            name='payrollgeneralsetting',
            table=None,
        ),
        migrations.AlterModelTable(
            name='payrollsettings',
            table=None,
        ),
        migrations.AlterModelTable(
            name='payslip',
            table=None,
        ),
        migrations.AlterModelTable(
            name='payslipautogenerate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='reimbursement',
            table=None,
        ),
        migrations.AlterModelTable(
            name='reimbursementfile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='reimbursementmultipleattachment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='reimbursementrequestcomment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='taxbracket',
            table=None,
        ),
        migrations.AlterModelTable(
            name='workrecord',
            table=None,
        ),
    ]
