# Generated by Django 5.2 on 2026-09-30 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_company_pan_hash_unique'),
        ('recruitment', '0006_alter_rejectreason_options_alter_skillzone_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='closed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='closed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='published_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='published_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_published', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='removed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='removed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_removed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'In Review'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('REMOVED', 'Removed')], db_index=True, default='DRAFT', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='submitted_for_review_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='submitted_for_review_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_submitted_for_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RecruitmentAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('JOB_OPENING_CREATED', 'Job opening created'), ('JOB_OPENING_UPDATED', 'Job opening updated'), ('JOB_OPENING_SUBMITTED_FOR_REVIEW', 'Job opening submitted for review'), ('JOB_OPENING_SENT_BACK_FOR_CHANGES', 'Job opening sent back for changes'), ('JOB_OPENING_PUBLISHED', 'Job opening published'), ('JOB_OPENING_CLOSED', 'Job opening closed'), ('JOB_OPENING_REMOVED', 'Job opening removed')], db_index=True, max_length=64, verbose_name='Event')),
                ('object_type', models.CharField(blank=True, max_length=64)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='recruitment.candidate', verbose_name='Candidate')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company', verbose_name='Company')),
                ('job_opening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='recruitment.recruitment', verbose_name='Job Opening')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='recruitment.stage', verbose_name='Stage')),
            ],
            options={
                'verbose_name': 'Recruitment Audit Event',
                'verbose_name_plural': 'Recruitment Audit Events',
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['job_opening', '-timestamp'], name='recruitment_job_ope_27f79b_idx'), models.Index(fields=['candidate', '-timestamp'], name='recruitment_candida_2460c2_idx'), models.Index(fields=['event_type', '-timestamp'], name='recruitment_event_t_00a318_idx'), models.Index(fields=['object_type', 'object_id'], name='recruitment_object__2ba2c1_idx')],
            },
        ),
    ]
