# Generated by Django 5.2 on 2026-09-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_backfill_job_opening_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='is_published',
            field=models.BooleanField(default=False, help_text="Derived from the job opening's status -- true only while it is Published. Do not set directly; use the lifecycle service.", verbose_name='Is Published'),
        ),
    ]
