# Generated by Django 5.2 on 2026-09-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_stamp_null_company_job_openings'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Internal only. Never shown to candidates.', max_digits=12, null=True, verbose_name='Budget (maximum)'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Internal only. Never shown to candidates.', max_digits=12, null=True, verbose_name='Budget (minimum)'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='contact_verification_required',
            field=models.BooleanField(default=False, help_text='When enabled, applicants are asked to verify their email address and mobile number. Verification never blocks submission.', verbose_name='Require contact verification'),
        ),
    ]
