# Generated by Django 5.2 on 2026-10-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0015_candidate_contact_verified_at_candidate_offered_ctc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentsurvey',
            name='allow_multiple_files',
            field=models.BooleanField(default=False, help_text='File-upload questions only.', verbose_name='Allow Multiple Files'),
        ),
        migrations.AddField(
            model_name='surveytemplatequestion',
            name='allow_multiple_files',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
