# Generated by Django 5.2 on 2026-10-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0016_recruitmentsurvey_allow_multiple_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcontactverification',
            name='otp_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
