# Generated by Django 5.2 on 2026-10-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0020_add_question_max_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='handoff_budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Budget (maximum)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='handoff_budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Budget (minimum)'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='handoff_budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Budget (maximum)'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='handoff_budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Budget (minimum)'),
        ),
    ]
