# Generated by Django 5.2 on 2026-10-06 06:13

from django.conf import settings
from django.db import migrations, models


def backfill(apps, schema_editor):
    """Type existing documents; add each candidate's resume as a document."""
    Doc = apps.get_model("recruitment", "CandidateDocument")
    Candidate = apps.get_model("recruitment", "Candidate")
    Doc.objects.filter(job_opening_question__form_type="form2").update(document_type="handoff")
    Doc.objects.filter(job_opening_question__form_type="form1").update(document_type="application")
    for cand in Candidate.objects.exclude(resume="").exclude(resume__isnull=True):
        if not Doc.objects.filter(candidate_id=cand, document_type="resume", is_active=True).exists():
            Doc.objects.create(
                candidate_id=cand, title="Resume", document=cand.resume.name,
                document_type="resume", status="approved", is_active=True,
                created_at=cand.created_at,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0023_audit_coverage_and_verification_candidate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedocument',
            name='document_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('application', 'Application form'), ('handoff', 'Hiring handoff'), ('uploaded', 'Uploaded by HR')], default='uploaded', max_length=20, verbose_name='Document type'),
        ),
        migrations.AddConstraint(
            model_name='candidatedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type', 'resume'), ('is_active', True)), fields=('candidate_id',), name='recruitment_one_active_resume_per_candidate'),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
