# Generated by Django 5.2 on 2026-10-06 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_phone_and_more'),
        ('recruitment', '0024_candidate_document_type_and_resume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentauditevent',
            name='event_type',
            field=models.CharField(choices=[('JOB_OPENING_CREATED', 'Job opening created'), ('JOB_OPENING_UPDATED', 'Job opening updated'), ('JOB_OPENING_SUBMITTED_FOR_REVIEW', 'Job opening submitted for review'), ('JOB_OPENING_SENT_BACK_FOR_CHANGES', 'Job opening sent back for changes'), ('JOB_OPENING_PUBLISHED', 'Job opening published'), ('JOB_OPENING_CLOSED', 'Job opening closed'), ('JOB_OPENING_REMOVED', 'Job opening removed'), ('QUESTION_CREATED', 'Screening question created'), ('QUESTION_UPDATED', 'Screening question updated'), ('QUESTION_ARCHIVED', 'Screening question archived'), ('TEMPLATE_CREATED', 'Screening template created'), ('TEMPLATE_UPDATED', 'Screening template updated'), ('QUESTION_ADDED_TO_TEMPLATE', 'Question added to template'), ('QUESTION_REMOVED_FROM_TEMPLATE', 'Question removed from template'), ('QUESTION_MADE_MANDATORY', 'Question made mandatory in template'), ('QUESTION_MADE_OPTIONAL', 'Question made optional in template'), ('JOB_OPENING_QUESTIONS_SNAPSHOTTED', 'Job opening questions snapshotted'), ('CANDIDATE_ANSWER_SUBMITTED', 'Candidate screening answers submitted'), ('CANDIDATE_ANSWER_UPDATED', 'Candidate screening answers updated'), ('CANDIDATE_CREATED', 'Candidate created'), ('CANDIDATE_MAPPED_TO_JOB_OPENING', 'Candidate mapped to job opening'), ('CANDIDATE_DOCUMENT_UPLOADED', 'Candidate document uploaded'), ('CANDIDATE_NOTE_ADDED', 'Candidate note added'), ('CANDIDATE_STAGE_CHANGED', 'Candidate stage changed'), ('CANDIDATE_REJECTED', 'Candidate rejected'), ('CANDIDATE_HIRED', 'Candidate hired'), ('CANDIDATE_EXPORTED', 'Candidate data exported'), ('CANDIDATE_ANONYMIZED', 'Candidate anonymized'), ('DOCUMENT_RETENTION_CLEANUP', 'Document retention cleanup'), ('APPLICATION_SUBMITTED', 'Application submitted'), ('CONTACT_VERIFICATION_STARTED', 'Contact verification started'), ('CONTACT_VERIFICATION_COMPLETED', 'Contact verification completed'), ('HANDOFF_FORM_SUBMITTED', 'Hiring handoff form submitted'), ('APPLICATION_LINK_SENT', 'Application link emailed'), ('CONTACT_EMAIL_VERIFIED', 'Email verified'), ('CONTACT_OTP_SENT', 'Verification code sent'), ('CONTACT_OTP_SEND_FAILED', 'Verification code could not be sent'), ('CONTACT_OTP_FAILED', 'Wrong verification code'), ('CANDIDATE_CONTACT_VERIFIED', 'Candidate contact verified'), ('STAGE_CREATED', 'Stage created'), ('STAGE_UPDATED', 'Stage updated'), ('STAGE_DELETED', 'Stage deleted'), ('STAGE_MANAGERS_CHANGED', 'Stage managers changed'), ('QUESTION_DELETED', 'Screening question deleted'), ('TEMPLATE_DELETED', 'Screening template deleted'), ('JOB_OPENING_QUESTION_ADDED', 'Question added to job opening'), ('JOB_OPENING_QUESTION_REMOVED', 'Question removed from job opening'), ('INTERVIEW_SCHEDULED', 'Interview scheduled'), ('INTERVIEW_RESCHEDULED', 'Interview rescheduled'), ('INTERVIEW_CANCELLED', 'Interview cancelled')], db_index=True, max_length=64, verbose_name='Event'),
        ),
        migrations.CreateModel(
            name='InterviewMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting for Google'), ('linked', 'Scheduled'), ('cancelled', 'Cancelled in Google')], default='pending', max_length=10)),
                ('google_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('meet_url', models.URLField(blank=True, default='')),
                ('event_url', models.URLField(blank=True, default='', max_length=500)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_meetings', to='recruitment.candidate')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('scheduled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employee.employee')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_meetings', to='recruitment.stage')),
            ],
            options={
                'verbose_name': 'Interview Meeting',
                'verbose_name_plural': 'Interview Meetings',
                'constraints': [models.UniqueConstraint(fields=('candidate', 'stage'), name='recruitment_one_interview_per_candidate_stage')],
            },
        ),
    ]
