# Generated by Django 5.2 on 2026-10-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0025_interview_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentgeneralsetting',
            name='career_page_domains',
            field=models.TextField(blank=True, default='', verbose_name='Career page domains'),
        ),
        migrations.AddField(
            model_name='recruitmentgeneralsetting',
            name='career_page_slug',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True, verbose_name='Career page link'),
        ),
    ]
