# Generated by Django 5.2 on 2026-10-07 09:36

import horilla.models
import recruitment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0026_career_page_domains_and_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(upload_to=horilla.models.upload_path, validators=[recruitment.models.validate_candidate_document], verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='historicalcandidate',
            name='resume',
            field=models.TextField(max_length=100, validators=[recruitment.models.validate_candidate_document], verbose_name='Resume'),
        ),
    ]
