# Generated by Django 5.2 on 2026-10-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0027_resume_pdf_size_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcontactverification',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
