# Generated by Django 5.2 on 2026-09-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krew_company_onboarding', '0020_companybankdetails_verified_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankverification',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Failure Reason'),
        ),
    ]
