# Generated by Django 5.2 on 2026-09-17 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krew_company_onboarding', '0023_rename_tables_to_krew_company_onboarding'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cashfreeapilog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='companybankdetails',
            table=None,
        ),
        migrations.AlterModelTable(
            name='companybankverification',
            table=None,
        ),
        migrations.AlterModelTable(
            name='companybrandedtemplate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='companycontract',
            table=None,
        ),
        migrations.AlterModelTable(
            name='companydeactivationrecord',
            table=None,
        ),
        migrations.AlterModelTable(
            name='companydocument',
            table=None,
        ),
        migrations.AlterModelTable(
            name='companypoccontact',
            table=None,
        ),
        migrations.AlterModelTable(
            name='companysignatory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='companystateregistration',
            table=None,
        ),
        migrations.AlterModelTable(
            name='gststateconfig',
            table=None,
        ),
    ]
