# Generated by Django 5.2 on 2026-09-18 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krew_company_onboarding', '0024_alter_cashfreeapilog_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybankdetails',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Used as the Cashfree beneficiary phone for bank verification.', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number.', regex='^\\d{10}$')], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='companypoccontact',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number.', regex='^\\d{10}$')], verbose_name='Mobile'),
        ),
    ]
