# Generated by Django 5.2 on 2026-09-11 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_onboarding', '0019_companystateregistration_drop_old_state_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankdetails',
            name='verified_attempt',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company_onboarding.companybankverification', verbose_name='Verified Attempt'),
        ),
    ]
