# Generated by Django 5.2 on 2026-10-01 06:51

import ckeditor_uploader.fields
import django.db.models.deletion
import horilla.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0018_company_pan_hash_unique'),
        ('employee', '0005_alter_employee_phone_and_more'),
        ('recruitment', '0006_alter_rejectreason_options_alter_skillzone_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('document_type', models.CharField(choices=[('OFFER_LETTER', 'Offer Letter'), ('RELIEVING_LETTER', 'Relieving Letter'), ('EXPERIENCE_LETTER', 'Experience Letter'), ('PAYSLIP', 'Payslip'), ('CUSTOM', 'Custom')], max_length=30, verbose_name='Document Type')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content')),
                ('is_default', models.BooleanField(default=False, help_text='The template used when generating a document of this type for this company, if more than one exists.', verbose_name='Is Default')),
                ('company', models.ForeignKey(blank=True, help_text='Leave blank to make this template available to every company.', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Document Template',
                'verbose_name_plural': 'Document Templates',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('document_type', models.CharField(choices=[('OFFER_LETTER', 'Offer Letter'), ('RELIEVING_LETTER', 'Relieving Letter'), ('EXPERIENCE_LETTER', 'Experience Letter'), ('PAYSLIP', 'Payslip'), ('CUSTOM', 'Custom')], max_length=30)),
                ('rendered_file', models.FileField(upload_to=horilla.models.upload_path, verbose_name='File')),
                ('context_snapshot', models.JSONField(blank=True, default=dict, help_text='The merge-field data used to render this document, for audit.', verbose_name='Merge Data')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to='recruitment.candidate', verbose_name='Candidate')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to='document_templates.documenttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Generated Document',
                'verbose_name_plural': 'Generated Documents',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TemplateAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('asset_type', models.CharField(choices=[('IMAGE', 'Image'), ('DOCUMENT', 'Document')], max_length=10, verbose_name='Asset Type')),
                ('file', models.FileField(upload_to=horilla.models.upload_path, verbose_name='File')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Template Asset',
                'verbose_name_plural': 'Template Assets',
                'ordering': ('-created_at',),
            },
        ),
    ]
