# Generated by Django 5.2 on 2026-10-06 06:31

import horilla.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='source_file',
            field=models.FileField(blank=True, help_text="The originally uploaded Word document, if this template's content was uploaded rather than typed in directly - kept for reference and re-upload, not used at render time.", null=True, upload_to=horilla.models.upload_path, verbose_name='Source .docx'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='unmapped_placeholders',
            field=models.JSONField(blank=True, default=list, help_text="{{ field }} placeholders found in content that aren't recognized merge fields for this document type - recomputed on every save.", verbose_name='Unmapped Placeholders'),
        ),
    ]
