# Generated by Django 5.2 on 2026-09-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_company_pan_hash_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetype',
            name='collar_category',
            field=models.CharField(blank=True, choices=[('WHITE_COLLAR', 'White Collar'), ('BLUE_COLLAR', 'Blue Collar'), ('GREY_COLLAR', 'Grey Collar')], max_length=15, null=True, verbose_name='Collar Category'),
        ),
    ]
