# Generated by Django 5.2 on 2026-09-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_employeetype_collar_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeshiftschedule',
            name='ot_start_time',
            field=models.TimeField(blank=True, help_text="Clock time after which hours worked count as overtime for this shift. Independent of the shift's own end time.", null=True, verbose_name='Overtime Start Time'),
        ),
    ]
