# Generated by Django 5.2 on 2026-09-24 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_employeeshiftschedule_ot_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeshiftschedule',
            name='ot_start_time',
        ),
    ]
