# Generated by Django 5.2 on 2026-09-23 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_employeetype_collar_category'),
        ('geofencing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='geofencing',
            name='unique_company_id_when_not_null_geofencing',
        ),
        migrations.RemoveField(
            model_name='geofencing',
            name='company_id',
        ),
        migrations.AddField(
            model_name='geofencing',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='geo_fencing_rules', to='base.company', verbose_name='Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geofencing',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_fencing_rules', to='base.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='geofencing',
            name='employee_type_category',
            field=models.CharField(blank=True, choices=[('WHITE_COLLAR', 'White Collar'), ('BLUE_COLLAR', 'Blue Collar'), ('GREY_COLLAR', 'Grey Collar')], max_length=15, null=True, verbose_name='Employee Type (exempt)'),
        ),
        migrations.AddField(
            model_name='geofencing',
            name='enforcement_mode',
            field=models.CharField(choices=[('REJECT', 'Reject the punch'), ('FLAG', 'Allow the punch and flag for review')], default='REJECT', max_length=10, verbose_name='On Violation'),
        ),
        migrations.AddField(
            model_name='geofencing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='geofencing',
            name='tier',
            field=models.CharField(choices=[('COMPANY', 'Company Default'), ('EMPLOYEE_TYPE', 'Employee Type Override'), ('DEPARTMENT', 'Department Override')], default='COMPANY', max_length=15, verbose_name='Tier'),
        ),
        migrations.AlterField(
            model_name='geofencing',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geofencing',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geofencing',
            name='radius_in_meters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geofencing',
            name='start',
            field=models.BooleanField(default=False, verbose_name='Enforcement Started'),
        ),
        migrations.AddConstraint(
            model_name='geofencing',
            constraint=models.UniqueConstraint(condition=models.Q(('tier', 'COMPANY')), fields=('company',), name='uniq_geofencing_company_tier'),
        ),
        migrations.AddConstraint(
            model_name='geofencing',
            constraint=models.UniqueConstraint(condition=models.Q(('tier', 'EMPLOYEE_TYPE')), fields=('company', 'employee_type_category'), name='uniq_geofencing_employee_type_tier'),
        ),
        migrations.AddConstraint(
            model_name='geofencing',
            constraint=models.UniqueConstraint(condition=models.Q(('tier', 'DEPARTMENT')), fields=('company', 'department'), name='uniq_geofencing_department_tier'),
        ),
    ]
