# Generated by Django 5.2 on 2026-09-22 09:47

import attendance.config_tiers
import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendanceconflictresolution_attendancedailyhours_and_more'),
        ('base', '0018_company_pan_hash_unique'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('tier', models.CharField(choices=[('company', 'Company Default'), ('employee_type', 'Employee Type Override'), ('department', 'Department Override')], default='company', max_length=15, verbose_name='Tier')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('mode', models.CharField(choices=[('shift_based', 'Shift-based'), ('flexible', 'Flexible')], default='shift_based', max_length=15, verbose_name='Attendance Type')),
                ('late_grace_minutes', models.PositiveIntegerField(default=0, verbose_name='Late-Mark Grace (minutes)')),
                ('flexible_ot_threshold_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Flexible OT Threshold (hours/day)')),
                ('auto_punch_out_cutoff_time', models.TimeField(blank=True, null=True, verbose_name='Flexible Auto Punch-out Cutoff')),
                ('total_work_hours_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total Work Hours Reference')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rule_sets', to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rule_sets', to='base.department', verbose_name='Department')),
                ('employee_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rule_sets', to='base.employeetype', verbose_name='Employee Type')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Attendance Rule Set',
                'verbose_name_plural': 'Attendance Rule Sets',
                'constraints': [models.UniqueConstraint(condition=models.Q(('tier', 'company')), fields=('company',), name='uniq_attendanceruleset_company_tier'), models.UniqueConstraint(condition=models.Q(('tier', 'employee_type')), fields=('company', 'employee_type'), name='uniq_attendanceruleset_employee_type_tier'), models.UniqueConstraint(condition=models.Q(('tier', 'department')), fields=('company', 'department'), name='uniq_attendanceruleset_department_tier')],
            },
            bases=(attendance.config_tiers.TieredConfigResolutionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PendingConfigChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('object_id', models.PositiveIntegerField()),
                ('tier', models.CharField(choices=[('company', 'Company Default'), ('employee_type', 'Employee Type Override'), ('department', 'Department Override')], max_length=15)),
                ('changes', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('previous_values', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('effective_date', models.DateField(db_index=True, verbose_name='Effective Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Pending Config Change',
                'verbose_name_plural': 'Pending Config Changes',
                'indexes': [models.Index(fields=['status', 'effective_date'], name='attendance__status_b72739_idx')],
            },
        ),
    ]
