# Generated by Django 5.2 on 2026-09-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendance_rule_set_and_pending_config_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceruleset',
            name='late_grace_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Late-Mark Grace (minutes)'),
        ),
    ]
