# Generated by Django 5.2 on 2026-09-22 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_attendanceruleset_late_grace_minutes'),
        ('base', '0018_company_pan_hash_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendanceruleset',
            name='uniq_attendanceruleset_company_tier',
        ),
        migrations.RemoveConstraint(
            model_name='attendanceruleset',
            name='uniq_attendanceruleset_employee_type_tier',
        ),
        migrations.RemoveConstraint(
            model_name='attendanceruleset',
            name='uniq_attendanceruleset_department_tier',
        ),
        migrations.AlterField(
            model_name='attendanceruleset',
            name='mode',
            field=models.CharField(choices=[('SHIFT_BASED', 'Shift-based'), ('FLEXIBLE', 'Flexible')], default='SHIFT_BASED', max_length=15, verbose_name='Attendance Type'),
        ),
        migrations.AlterField(
            model_name='attendanceruleset',
            name='tier',
            field=models.CharField(choices=[('COMPANY', 'Company Default'), ('EMPLOYEE_TYPE', 'Employee Type Override'), ('DEPARTMENT', 'Department Override')], default='COMPANY', max_length=15, verbose_name='Tier'),
        ),
        migrations.AlterField(
            model_name='pendingconfigchange',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='pendingconfigchange',
            name='tier',
            field=models.CharField(choices=[('COMPANY', 'Company Default'), ('EMPLOYEE_TYPE', 'Employee Type Override'), ('DEPARTMENT', 'Department Override')], max_length=15),
        ),
        migrations.AddConstraint(
            model_name='attendanceruleset',
            constraint=models.UniqueConstraint(condition=models.Q(('tier', 'COMPANY')), fields=('company',), name='uniq_attendanceruleset_company_tier'),
        ),
        migrations.AddConstraint(
            model_name='attendanceruleset',
            constraint=models.UniqueConstraint(condition=models.Q(('tier', 'EMPLOYEE_TYPE')), fields=('company', 'employee_type'), name='uniq_attendanceruleset_employee_type_tier'),
        ),
        migrations.AddConstraint(
            model_name='attendanceruleset',
            constraint=models.UniqueConstraint(condition=models.Q(('tier', 'DEPARTMENT')), fields=('company', 'department'), name='uniq_attendanceruleset_department_tier'),
        ),
    ]
