# Generated by Django 5.2 on 2026-09-23 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_remove_attendanceruleset_uniq_attendanceruleset_company_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_rule_set',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='attendance.attendanceruleset', verbose_name='Attendance Rule Set (snapshot)'),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='attendance_rule_set',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='attendance.attendanceruleset', verbose_name='Attendance Rule Set (snapshot)'),
        ),
    ]
