# Generated by Django 5.2 on 2026-09-23 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_attendance_rule_set_snapshot'),
        ('base', '0019_employeetype_collar_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendanceruleset',
            name='uniq_attendanceruleset_employee_type_tier',
        ),
        migrations.RemoveField(
            model_name='attendanceruleset',
            name='employee_type',
        ),
        migrations.AddField(
            model_name='attendanceruleset',
            name='employee_type_category',
            field=models.CharField(blank=True, choices=[('WHITE_COLLAR', 'White Collar'), ('BLUE_COLLAR', 'Blue Collar'), ('GREY_COLLAR', 'Grey Collar')], max_length=15, null=True, verbose_name='Employee Type'),
        ),
        migrations.AddConstraint(
            model_name='attendanceruleset',
            constraint=models.UniqueConstraint(condition=models.Q(('tier', 'EMPLOYEE_TYPE')), fields=('company', 'employee_type_category'), name='uniq_attendanceruleset_employee_type_tier'),
        ),
    ]
