# Generated by Django 5.2 on 2026-09-23 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_remove_attendanceruleset_uniq_attendanceruleset_employee_type_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancegeneralsetting',
            name='auto_punch_out_enabled',
            field=models.BooleanField(default=True, help_text='Company-wide switch for Auto Punch-out. Turning this off overrides every other Auto Punch-out setting for this company.', verbose_name='Enable Auto Punch-out'),
        ),
        migrations.AddField(
            model_name='attendancegeneralsetting',
            name='no_shift_auto_punch_out_time',
            field=models.TimeField(default=datetime.time(23, 59), help_text='Cutoff time used to auto-close an open session for an employee with no shift assigned at all.', verbose_name='No-Shift Auto Punch-out Time'),
        ),
    ]
