# Generated by Django 5.2 on 2026-09-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_attendancegeneralsetting_auto_punch_out_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='geo_fence_unverified',
            field=models.BooleanField(default=False, help_text="A punch's location could not be checked against the configured boundary (not the same as a confirmed violation).", verbose_name='Geo-fence Unverified'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='geo_fence_violation',
            field=models.BooleanField(default=False, help_text="A punch was confirmed outside the configured boundary and the boundary's enforcement mode is Flag, not Reject.", verbose_name='Geo-fence Violation'),
        ),
        migrations.AddField(
            model_name='attendanceactivity',
            name='clock_in_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Clock-In Latitude'),
        ),
        migrations.AddField(
            model_name='attendanceactivity',
            name='clock_in_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Clock-In Longitude'),
        ),
        migrations.AddField(
            model_name='attendanceactivity',
            name='clock_out_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Clock-Out Latitude'),
        ),
        migrations.AddField(
            model_name='attendanceactivity',
            name='clock_out_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Clock-Out Longitude'),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='geo_fence_unverified',
            field=models.BooleanField(default=False, help_text="A punch's location could not be checked against the configured boundary (not the same as a confirmed violation).", verbose_name='Geo-fence Unverified'),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='geo_fence_violation',
            field=models.BooleanField(default=False, help_text="A punch was confirmed outside the configured boundary and the boundary's enforcement mode is Flag, not Reject.", verbose_name='Geo-fence Violation'),
        ),
        migrations.AddField(
            model_name='historicalattendanceactivity',
            name='clock_in_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Clock-In Latitude'),
        ),
        migrations.AddField(
            model_name='historicalattendanceactivity',
            name='clock_in_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Clock-In Longitude'),
        ),
        migrations.AddField(
            model_name='historicalattendanceactivity',
            name='clock_out_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Clock-Out Latitude'),
        ),
        migrations.AddField(
            model_name='historicalattendanceactivity',
            name='clock_out_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Clock-Out Longitude'),
        ),
    ]
