# Generated by Django 5.2 on 2026-09-23 11:35

import attendance.methods.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_attendance_geo_fence_unverified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceruleset',
            name='validation_threshold',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[attendance.methods.utils.validate_time_format], verbose_name='Worked Hours Auto-Validate Till'),
        ),
    ]
