# Generated by Django 5.2 on 2026-09-24 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_attendanceruleset_validation_threshold'),
        ('base', '0019_employeetype_collar_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendanceruleset',
            name='uniq_attendanceruleset_company_tier',
        ),
        migrations.RemoveConstraint(
            model_name='attendanceruleset',
            name='uniq_attendanceruleset_department_tier',
        ),
        migrations.RemoveConstraint(
            model_name='attendanceruleset',
            name='uniq_attendanceruleset_employee_type_tier',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_rule_set_version',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Attendance Rule Set Version (snapshot)'),
        ),
        migrations.AddField(
            model_name='attendanceruleset',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='attendance_rule_set_version',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Attendance Rule Set Version (snapshot)'),
        ),
        migrations.AddConstraint(
            model_name='attendanceruleset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('tier', 'COMPANY')), fields=('company',), name='uniq_attendanceruleset_company_tier'),
        ),
        migrations.AddConstraint(
            model_name='attendanceruleset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('tier', 'EMPLOYEE_TYPE')), fields=('company', 'employee_type_category'), name='uniq_attendanceruleset_employee_type_tier'),
        ),
        migrations.AddConstraint(
            model_name='attendanceruleset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('tier', 'DEPARTMENT')), fields=('company', 'department'), name='uniq_attendanceruleset_department_tier'),
        ),
    ]
