# Generated by Django 5.2 on 2026-09-24 05:27

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_remove_attendanceruleset_uniq_attendanceruleset_company_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_rule_set_effective_values',
            field=models.JSONField(blank=True, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Attendance Rule Set Effective Values (snapshot)'),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='attendance_rule_set_effective_values',
            field=models.JSONField(blank=True, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Attendance Rule Set Effective Values (snapshot)'),
        ),
    ]
