# Generated by Django 5.2 on 2026-09-24 06:00

import attendance.methods.utils
import django.core.serializers.json
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_attendance_attendance_rule_set_effective_values_and_more'),
        ('base', '0019_employeetype_collar_category'),
        ('horilla_audit', '0003_alter_historytrackingfields_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAttendanceRuleSet',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Created At')),
                ('history_title', models.CharField(blank=True, max_length=20, null=True)),
                ('history_description', models.TextField(null=True)),
                ('history_highlight', models.BooleanField(default=False, null=True)),
                ('tier', models.CharField(choices=[('COMPANY', 'Company Default'), ('EMPLOYEE_TYPE', 'Employee Type Override'), ('DEPARTMENT', 'Department Override')], default='COMPANY', max_length=15, verbose_name='Tier')),
                ('employee_type_category', models.CharField(blank=True, choices=[('WHITE_COLLAR', 'White Collar'), ('BLUE_COLLAR', 'Blue Collar'), ('GREY_COLLAR', 'Grey Collar')], max_length=15, null=True, verbose_name='Employee Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('mode', models.CharField(choices=[('SHIFT_BASED', 'Shift-based'), ('FLEXIBLE', 'Flexible')], default='SHIFT_BASED', max_length=15, verbose_name='Attendance Type')),
                ('late_grace_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Late-Mark Grace (minutes)')),
                ('flexible_ot_threshold_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Flexible OT Threshold (hours/day)')),
                ('auto_punch_out_cutoff_time', models.TimeField(blank=True, null=True, verbose_name='Flexible Auto Punch-out Cutoff')),
                ('total_work_hours_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total Work Hours Reference')),
                ('validation_threshold', models.CharField(blank=True, max_length=10, null=True, validators=[attendance.methods.utils.validate_time_format], verbose_name='Worked Hours Auto-Validate Till')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Attendance Rule Set',
                'verbose_name_plural': 'historical Attendance Rule Sets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name='attendanceruleset',
            name='uniq_attendanceruleset_company_tier',
        ),
        migrations.RemoveConstraint(
            model_name='attendanceruleset',
            name='uniq_attendanceruleset_employee_type_tier',
        ),
        migrations.RemoveConstraint(
            model_name='attendanceruleset',
            name='uniq_attendanceruleset_department_tier',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_rule_set_effective_values',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_rule_set_version',
        ),
        migrations.RemoveField(
            model_name='attendanceruleset',
            name='version',
        ),
        migrations.RemoveField(
            model_name='historicalattendance',
            name='attendance_rule_set_effective_values',
        ),
        migrations.RemoveField(
            model_name='historicalattendance',
            name='attendance_rule_set_version',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_rule_set_snapshot',
            field=models.JSONField(blank=True, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Attendance Rule Set Snapshot'),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='attendance_rule_set_snapshot',
            field=models.JSONField(blank=True, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Attendance Rule Set Snapshot'),
        ),
        migrations.AddConstraint(
            model_name='attendanceruleset',
            constraint=models.UniqueConstraint(condition=models.Q(('tier', 'COMPANY')), fields=('company',), name='uniq_attendanceruleset_company_tier'),
        ),
        migrations.AddConstraint(
            model_name='attendanceruleset',
            constraint=models.UniqueConstraint(condition=models.Q(('tier', 'EMPLOYEE_TYPE')), fields=('company', 'employee_type_category'), name='uniq_attendanceruleset_employee_type_tier'),
        ),
        migrations.AddConstraint(
            model_name='attendanceruleset',
            constraint=models.UniqueConstraint(condition=models.Q(('tier', 'DEPARTMENT')), fields=('company', 'department'), name='uniq_attendanceruleset_department_tier'),
        ),
        migrations.AddField(
            model_name='historicalattendanceruleset',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='historicalattendanceruleset',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='historicalattendanceruleset',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='historicalattendanceruleset',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_set', to='attendance.attendanceruleset'),
        ),
        migrations.AddField(
            model_name='historicalattendanceruleset',
            name='history_tags',
            field=models.ManyToManyField(to='horilla_audit.audittag'),
        ),
        migrations.AddField(
            model_name='historicalattendanceruleset',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalattendanceruleset',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
    ]
