# Generated by Django 5.2 on 2026-09-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_historicalattendanceruleset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceruleset',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='historicalattendanceruleset',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='Version'),
        ),
    ]
