# Generated by Django 5.2 on 2026-09-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_attendanceruleset_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceruleset',
            name='flexible_ot_auto_approve_buffer_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Flexible OT Auto-Approve Buffer (hours)'),
        ),
        migrations.AddField(
            model_name='attendanceruleset',
            name='shift_ot_auto_approve_buffer_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Shift-based OT Auto-Approve Buffer (minutes)'),
        ),
        migrations.AddField(
            model_name='attendanceruleset',
            name='shift_ot_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Shift-based OT Start Time'),
        ),
        migrations.AddField(
            model_name='attendanceruleset',
            name='track_overtime',
            field=models.BooleanField(blank=True, null=True, verbose_name='Track Overtime'),
        ),
        migrations.AddField(
            model_name='historicalattendanceruleset',
            name='flexible_ot_auto_approve_buffer_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Flexible OT Auto-Approve Buffer (hours)'),
        ),
        migrations.AddField(
            model_name='historicalattendanceruleset',
            name='shift_ot_auto_approve_buffer_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Shift-based OT Auto-Approve Buffer (minutes)'),
        ),
        migrations.AddField(
            model_name='historicalattendanceruleset',
            name='shift_ot_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Shift-based OT Start Time'),
        ),
        migrations.AddField(
            model_name='historicalattendanceruleset',
            name='track_overtime',
            field=models.BooleanField(blank=True, null=True, verbose_name='Track Overtime'),
        ),
    ]
