# Generated by Django 5.2 on 2026-09-24 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_attendanceruleset_flexible_ot_auto_approve_buffer_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceruleset',
            name='shift_ot_start_time',
        ),
        migrations.RemoveField(
            model_name='historicalattendanceruleset',
            name='shift_ot_start_time',
        ),
    ]
