# Generated by Django 5.2 on 2026-09-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_remove_attendanceruleset_shift_ot_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceruleset',
            name='flexible_ot_threshold_hours',
        ),
        migrations.RemoveField(
            model_name='historicalattendanceruleset',
            name='flexible_ot_threshold_hours',
        ),
        migrations.AddField(
            model_name='attendanceruleset',
            name='ot_threshold_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Overtime Threshold (hours)'),
        ),
        migrations.AddField(
            model_name='historicalattendanceruleset',
            name='ot_threshold_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Overtime Threshold (hours)'),
        ),
    ]
