# Generated by Django 5.2 on 2026-09-24 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_remove_attendanceruleset_flexible_ot_threshold_hours_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('employee', '0005_alter_employee_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceruleset',
            name='regularization_enabled',
            field=models.BooleanField(blank=True, null=True, verbose_name='Enable Regularization'),
        ),
        migrations.AddField(
            model_name='attendanceruleset',
            name='regularization_monthly_cap',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Regularization Monthly Cap'),
        ),
        migrations.AddField(
            model_name='historicalattendanceruleset',
            name='regularization_enabled',
            field=models.BooleanField(blank=True, null=True, verbose_name='Enable Regularization'),
        ),
        migrations.AddField(
            model_name='historicalattendanceruleset',
            name='regularization_monthly_cap',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Regularization Monthly Cap'),
        ),
        migrations.CreateModel(
            name='ApprovalDelegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to='employee.employee', verbose_name='Delegate')),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to='employee.employee', verbose_name='Delegator')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Approval Delegate',
                'verbose_name_plural': 'Approval Delegates',
                'permissions': [('can_be_delegate', 'Can be selected as an approval delegate')],
            },
        ),
        migrations.CreateModel(
            name='RegularizationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('reason_code', models.CharField(choices=[('TIME_CORRECTION', 'Time Correction'), ('AUTO_CLOSE_DISPUTE', 'Auto Punch-out Dispute'), ('GEO_VIOLATION_DISPUTE', 'Geo-location Dispute'), ('OVERTIME_DENIAL_DISPUTE', 'Overtime Decision Dispute')], max_length=25, verbose_name='Reason')),
                ('reason', models.TextField(verbose_name='Explanation')),
                ('corrected_clock_in', models.TimeField(blank=True, null=True)),
                ('corrected_clock_in_date', models.DateField(blank=True, null=True)),
                ('corrected_clock_out', models.TimeField(blank=True, null=True)),
                ('corrected_clock_out_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('overtime_decision', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], max_length=10, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularization_requests', to='attendance.attendance', verbose_name='Attendance')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularization_requests', to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employee.employee', verbose_name='Resolved By')),
            ],
            options={
                'verbose_name': 'Regularization Request',
                'verbose_name_plural': 'Regularization Requests',
            },
        ),
    ]
