# Generated by Django 5.2 on 2026-09-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_attendanceruleset_regularization_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceruleset',
            name='irregularities_enabled',
            field=models.BooleanField(blank=True, null=True, verbose_name='Enable Irregularities'),
        ),
        migrations.AddField(
            model_name='historicalattendanceruleset',
            name='irregularities_enabled',
            field=models.BooleanField(blank=True, null=True, verbose_name='Enable Irregularities'),
        ),
        migrations.AlterField(
            model_name='attendancelatecomeearlyout',
            name='type',
            field=models.CharField(choices=[('late_come', 'Late Arrival'), ('early_out', 'Early Departure'), ('flexible_shortfall', 'Flexible Hours Shortfall')], max_length=20, verbose_name='Type'),
        ),
    ]
