# Generated by Django 5.2 on 2026-09-24 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_attendanceruleset_irregularities_enabled_and_more'),
        ('employee', '0005_alter_employee_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundAttendanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('kind', models.CharField(choices=[('LATE_COME_EARLY_OUT', 'Late-Come / Early-Out Flagging'), ('OVERTIME_ACCOUNT_UPDATE', 'Monthly Overtime Account Update')], max_length=25, verbose_name='Kind')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_tasks', to='attendance.attendance', verbose_name='Attendance')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Background Attendance Task',
                'verbose_name_plural': 'Background Attendance Tasks',
            },
        ),
        migrations.CreateModel(
            name='BackgroundAttendanceTaskRetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('reset_at', models.DateTimeField(auto_now_add=True)),
                ('previous_status', models.CharField(max_length=10)),
                ('previous_attempts', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('reset_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employee.employee', verbose_name='Reset By')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retry_log', to='attendance.backgroundattendancetask', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Background Attendance Task Retry Log',
                'verbose_name_plural': 'Background Attendance Task Retry Logs',
            },
        ),
    ]
