# Generated by Django 5.2 on 2026-09-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_backgroundattendancetask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundattendancetask',
            name='payload',
        ),
        migrations.AlterField(
            model_name='backgroundattendancetask',
            name='kind',
            field=models.CharField(choices=[('LATE_COME_EARLY_OUT', 'Late-Come / Early-Out Flagging')], max_length=25, verbose_name='Kind'),
        ),
    ]
