# Generated by Django 5.2 on 2026-09-29 09:34

from django.db import migrations, models


def rename_done_to_success(apps, schema_editor):
    BackgroundAttendanceTask = apps.get_model("attendance", "BackgroundAttendanceTask")
    BackgroundAttendanceTask.objects.filter(status="DONE").update(status="SUCCESS")


def rename_success_to_done(apps, schema_editor):
    BackgroundAttendanceTask = apps.get_model("attendance", "BackgroundAttendanceTask")
    BackgroundAttendanceTask.objects.filter(status="SUCCESS").update(status="DONE")


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_remove_backgroundattendancetask_payload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundattendancetask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.RunPython(rename_done_to_success, rename_success_to_done),
    ]
