# Generated by Django 5.2 on 2026-10-05 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0027_background_attendance_task_status_success'),
        ('employee', '0005_alter_employee_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('action_type', models.CharField(choices=[('PUNCH_IN', 'Punch In'), ('PUNCH_OUT', 'Punch Out'), ('AUTO_PUNCH_OUT', 'Auto Punch-out'), ('ATTENDANCE_TYPE_SWITCH', 'Attendance Type Switch'), ('VALIDATION_AUTO_PASS', 'Validation Auto-Pass'), ('OVERTIME_AUTO_APPROVE', 'Overtime Auto-Approve'), ('MANUAL_CREATE_OVERRIDE', 'Manual Create/Override'), ('REGULARIZATION_DECISION', 'Regularization Decision'), ('BULK_IMPORT', 'Bulk Import')], max_length=30, verbose_name='Action Type')),
                ('affected_employee_ids', models.JSONField(default=list, verbose_name='Affected Employees')),
                ('what_changed', models.CharField(max_length=255, verbose_name='What Changed')),
                ('source', models.CharField(max_length=50, verbose_name='Source')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_activity_actions', to='employee.employee', verbose_name='Actor')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Attendance Activity Log',
                'verbose_name_plural': 'Attendance Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
