# Generated by Django 5.2 on 2026-10-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_attendanceactivitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-attendance_date', 'employee_id__employee_first_name', 'attendance_clock_in'], 'permissions': [('change_validateattendance', 'Validate Attendance'), ('change_approveovertime', 'Change Approve Overtime'), ('can_create_attendance', 'Can manually create/override attendance')], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AddField(
            model_name='attendance',
            name='creation_source',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manually Created')], max_length=20, null=True, verbose_name='Creation Source'),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='creation_source',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manually Created')], max_length=20, null=True, verbose_name='Creation Source'),
        ),
    ]
