# Generated by Django 5.2 on 2026-10-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_alter_attendance_options_attendance_creation_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='overtime_decision',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10, verbose_name='Overtime Decision'),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='overtime_decision',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10, verbose_name='Overtime Decision'),
        ),
        migrations.AlterField(
            model_name='attendanceactivitylog',
            name='action_type',
            field=models.CharField(choices=[('PUNCH_IN', 'Punch In'), ('PUNCH_OUT', 'Punch Out'), ('AUTO_PUNCH_OUT', 'Auto Punch-out'), ('ATTENDANCE_TYPE_SWITCH', 'Attendance Type Switch'), ('VALIDATION_AUTO_PASS', 'Validation Auto-Pass'), ('OVERTIME_AUTO_APPROVE', 'Overtime Auto-Approve'), ('MANUAL_CREATE_OVERRIDE', 'Manual Create/Override'), ('REGULARIZATION_DECISION', 'Regularization Decision'), ('OVERTIME_MANUAL_DECISION', 'Overtime Manual Decision'), ('BULK_IMPORT', 'Bulk Import')], max_length=30, verbose_name='Action Type'),
        ),
    ]
