# Generated by Django 5.2 on 2026-10-06 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_attendance_overtime_decision_and_more'),
        ('base', '0021_remove_employeeshiftschedule_ot_start_time'),
        ('employee', '0005_alter_employee_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollReadinessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('start_date', models.DateField(verbose_name='Period Start')),
                ('end_date', models.DateField(verbose_name='Period End')),
                ('locked_at', models.DateTimeField(auto_now_add=True, verbose_name='Locked At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('locked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee', verbose_name='Locked By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollReadinessSnapshotRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('date', models.DateField(verbose_name='Date')),
                ('day_type', models.CharField(choices=[('WORKED', 'Worked'), ('HOLIDAY', 'Holiday'), ('WEEKLY_OFF', 'Weekly-Off'), ('APPROVED_LEAVE', 'Approved Leave'), ('EXCEPTION', 'Exception')], max_length=20, verbose_name='Day Type')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Check-in')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Check-out')),
                ('worked_hours', models.CharField(default='00:00', max_length=10)),
                ('overtime_hours', models.CharField(default='00:00', max_length=10)),
                ('was_exception', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='attendance.payrollreadinesssnapshot')),
            ],
            options={
                'ordering': ['employee_id', 'date'],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollreadinesssnapshot',
            constraint=models.UniqueConstraint(fields=('company', 'start_date', 'end_date'), name='unique_payroll_readiness_period'),
        ),
    ]
