# Generated by Django 5.2 on 2026-10-08 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0031_payrollreadinesssnapshot_payrollreadinesssnapshotrow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceruleset',
            name='validation_threshold',
        ),
        migrations.RemoveField(
            model_name='historicalattendanceruleset',
            name='validation_threshold',
        ),
    ]
