# Generated by Django 5.2 on 2026-10-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0032_remove_attendanceruleset_validation_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceruleset',
            name='ot_threshold_hours',
        ),
        migrations.RemoveField(
            model_name='historicalattendanceruleset',
            name='ot_threshold_hours',
        ),
        migrations.AddField(
            model_name='attendanceruleset',
            name='ot_threshold_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Overtime Threshold (HH:MM)'),
        ),
        migrations.AddField(
            model_name='historicalattendanceruleset',
            name='ot_threshold_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Overtime Threshold (HH:MM)'),
        ),
    ]
