# Generated by Django 5.2 on 2026-10-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0033_remove_attendanceruleset_ot_threshold_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceruleset',
            name='ot_threshold_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Overtime Threshold (minutes)'),
        ),
        migrations.AlterField(
            model_name='historicalattendanceruleset',
            name='ot_threshold_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Overtime Threshold (minutes)'),
        ),
    ]
